// This will be auto-generated by i18next-cli types
// Custom type augmentations can be added here
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: {
      translation: typeof import('../locales/en/translation.json');
    };
  }
}
